version: '3'

networks:
  ghana-network:
    external: true
services:
  one:
    build:
      dockerfile: Dockerfile
    image: ghana-1
    container_name: ghana-container-1
    networks:
      - ghana-network
    ports:
    - "8080:8080"

  two:
    build:
      dockerfile: Dockerfile
    image: ghana-2
    container_name: ghana-container-2
    networks:
      - ghana-network
    ports:
    - "9090:8080"
